import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

# [font.normal]
# family = "Iosevka Nerd Font Mono"
# style = "Regular"

[window]
option_as_alt = "Both"
