# Base16 Default Dark - alacritty color config
# Chris Kempson (http://chriskempson.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black = '#181818'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#d8d8d8'

# Bright colors
[colors.bright]
black = '#585858'
red = '#dc9656'
green = '#282828'
yellow = '#383838'
blue = '#b8b8b8'
magenta = '#e8e8e8'
cyan = '#a16946'
white = '#f8f8f8'
