[[language]]
name = "python"
language-servers = ["ruff", "pyright"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

# [language-server.pylsp.config.pylsp]
# plugins.pyls_mypy.enabled = true
# plugins.pyls_mypy.live_mode = true

[language-server.ruff-lsp]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
